version: '3'

services:
  streaming-nodejs-builder:
    image: ${REGISTRY_HOST}/streaming-nodejs-builder
    container_name: streaming-nodejs-builder
    build:
      context: ./docker
      dockerfile: ./nodejs-builder.Dockerfile
      args:
        - REGISTRY_HOST=${REGISTRY_HOST}
        - NODE_IMAGE=${NODE_IMAGE}
  streaming-nodejs-runner:
    image: ${REGISTRY_HOST}/streaming-nodejs-runner
    container_name: streaming-nodejs-runner
    build:
      context: ./docker
      dockerfile: ./nodejs-runner.Dockerfile
      args:
        - REGISTRY_HOST=${REGISTRY_HOST}
        - NODE_IMAGE=${NODE_IMAGE}
