version: '3'

services:
  nginx-ts:
    build:
      context: ./nginx-ts
      dockerfile: ./Dockerfile
      args:
        - REGISTRY_HOST=${REGISTRY_HOST}
        - NODE_IMAGE=${NODE_IMAGE}
        - PORT=${NGINX_TS_PORT}
  # nginx-rtmp:
  #   build:
  #     context: ./nginx-rtmp
