version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq:v1.0.0-compat
    command: /nsqlookupd
    ports:
      - 4160
      - ${NSQLOOKUPD_PORT}
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - ${NSQD_PORT}
      - 4151
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:${NSQLOOKUPD_PORT}
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
