version: '3'

services:
  registry:
    image: ${REGISTRY_HOST}/registry
    container_name: registry
    restart: always
    ports:
      - 5001:5000
    # environment:
    #   REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    #   REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    # volumes:
    #   - /path/data:/var/lib/registry
    #   - /path/certs:/certs
    #   - /path/auth:/auth
  portainer:
    image: ${REGISTRY_HOST}/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
