ARG REGISTRY_HOST
ARG NODE_IMAGE
ARG PORT=3004
ARG PORT_MIN=1101
ARG PORT_MAX=1400



# FROM ${REGISTRY_HOST}/streaming-types:latest as types

FROM ${NODE_IMAGE} as deps
WORKDIR /usr/src/

FROM ${REGISTRY_HOST}/streaming-nodejs-builder as builder

FROM ${REGISTRY_HOST}/streaming-nodejs-runner as runner
RUN apt-get update && \
    apt-get install -y libav-tools && \
    apt-get install -y ffmpeg
EXPOSE ${PORT}
EXPOSE 1101-1400
CMD [ "npm", "start" ]
